### ISSUE TITLE
Unable to generalize model members.

### ISSUE THREAD

**Issue by sdalexandre** [uon-team/model#1]
I'm trying to do the following:
```
export class CommonModel {

    @Member()
    createdOn: Date;

    @Member()
    updatedOn: Date;
}

@Model()
export class SubscriptionSeat extends CommonModel {

    @ID()
    id: string;
}

```
But I'm getting the following error:
```
Error: Can only have 1 Member decorator on a property, got 2 on SubscriptionSeat.id
    at eval (webpack:///./node_modules/@uon/model/meta/model.decorator.js?:29:19)
```

I have debug and the property id get included twice: filtered = [{"key":"id"},{"key":"id"}]

What am I doing wrong? Is it supported?

**Comment by uon-io** [comment]
This will be possible in the next update 724e837c1e1fcda25e81f25bbea055994d368756
